### PR TITLE
Replace original Readme file

### PR DESCRIPTION
**Pull request by ll7**
- Rename `README.md` to `README_old.md`.
- Create a new, simplified but "up-to-date" `README.md`

### CODE REVIEW

**Comment by Bonifatius94** [comment]
keep the readme to the point (good work). delete history entirely

**Comment by ll7** [comment]
If we delete the history section and the `README_old` we also lose the acknowledgements and citations. I know that you like your repositories as clean as possible, but I think that these acknowledgements are important if we ever want to publish anything while using any code base or ideas from these references.

**Comment by Bonifatius94** [comment]
Sure, we can have acknowledgements and theoretical background in another markdown  file. Also we can add the images from my M.Sc. presentation that outline the forces.

**Comment by ll7** [comment]
Okay, that is a good compromise.

**Comment by Bonifatius94** [comment]
I've already cleaned up the README and pushed it on the main branch. Soon, I'll upload a THEORY.md as well. Thanks for your contribution.

**Pull request closed without merging**
